spring.application.name=lumenstore-api
logging.level.org.springframework.security=DEBUG

# Desactivar validación de esquema de Flyway (tu BD ya está creada manualmente)
spring.flyway.enabled=false

# Hibernate validará contra tu BD real
spring.jpa.hibernate.ddl-auto=validate