import { ISale, ISaleDetail, IShipment, IPaymentTransaction, IVoucher } from './sales';

// ─── Mock Sale Details ───
const mockDetails: ISaleDetail[] = [
  {
    id: 1,
    saleId: 1,
    variantId: 101,
    quantity: 2,
    unitPrice: 89.9,
    discountAmount: 0,
    subtotal: 179.8,
    productName: 'Camisa Algodón Premium',
    sku: 'CMP-BLK-S-001',
    imageUrl: '',
    sizeName: 'S',
    colorName: 'Negro',
    colorHex: '#000000',
  },
  {
    id: 2,
    saleId: 1,
    variantId: 102,
    quantity: 1,
    unitPrice: 129.0,
    discountAmount: 10.0,
    subtotal: 119.0,
    productName: 'Pantalón Chino Slim Fit',
    sku: 'PCH-NAV-M-002',
    imageUrl: '',
    sizeName: 'M',
    colorName: 'Azul Marino',
    colorHex: '#1a2744',
  },
  {
    id: 3,
    saleId: 2,
    variantId: 201,
    quantity: 3,
    unitPrice: 45.5,
    discountAmount: 5.5,
    subtotal: 131.0,
    productName: 'Polera Básica Algodón',
    sku: 'PBA-WHT-L-003',
    imageUrl: '',
    sizeName: 'L',
    colorName: 'Blanco',
    colorHex: '#ffffff',
  },
  {
    id: 4,
    saleId: 3,
    variantId: 301,
    quantity: 1,
    unitPrice: 249.0,
    discountAmount: 0,
    subtotal: 249.0,
    productName: 'Chaqueta Cuero Sintético',
    sku: 'CHC-BRN-M-004',
    imageUrl: '',
    sizeName: 'M',
    colorName: 'Marrón',
    colorHex: '#8B4513',
  },
  {
    id: 5,
    saleId: 4,
    variantId: 401,
    quantity: 1,
    unitPrice: 79.9,
    discountAmount: 0,
    subtotal: 79.9,
    productName: 'Vestido Floral Verano',
    sku: 'VFL-RED-S-005',
    imageUrl: '',
    sizeName: 'S',
    colorName: 'Rojo',
    colorHex: '#dc2626',
  },
  {
    id: 6,
    saleId: 5,
    variantId: 501,
    quantity: 4,
    unitPrice: 35.0,
    discountAmount: 0,
    subtotal: 140.0,
    productName: 'Medias Algodón Pack x4',
    sku: 'MED-GRY-U-006',
    sizeName: 'Único',
    colorName: 'Gris',
    colorHex: '#9ca3af',
  },
  {
    id: 7,
    saleId: 5,
    variantId: 502,
    quantity: 1,
    unitPrice: 59.0,
    discountAmount: 0,
    subtotal: 59.0,
    productName: 'Gorra Trucker',
    sku: 'GTR-BLK-U-007',
    sizeName: 'Único',
    colorName: 'Negro',
    colorHex: '#000000',
  },
];

// ─── Mock Shipments ───
const mockShipments: IShipment[] = [
  {
    id: 1,
    saleId: 4,
    trackingNumber: 'OLV-2026-001234',
    carrier: 'Olva Courier',
    status: 'delivered',
    shippedAt: '2026-03-10T10:30:00Z',
    deliveredAt: '2026-03-14T14:20:00Z',
    address: {
      street: 'Av. Larco 123',
      city: 'Miraflores',
      state: 'Lima',
      postalCode: '15074',
      country: 'Perú',
    },
  },
  {
    id: 2,
    saleId: 4,
    trackingNumber: 'SHL-2026-005678',
    carrier: 'Shalom',
    status: 'in_transit',
    shippedAt: '2026-03-12T08:15:00Z',
    deliveredAt: '',
    address: {
      street: 'Av. Larco 123',
      city: 'Miraflores',
      state: 'Lima',
      postalCode: '15074',
      country: 'Perú',
    },
  },
];

// ─── Mock Payment Transactions ───
const mockPayments: IPaymentTransaction[] = [
  {
    id: 1,
    saleId: 1,
    transactionId: 'TXN-20260301-001',
    amount: 298.8,
    status: 'completed',
    paymentMethod: 'card',
    responseData: JSON.stringify({
      status: 'approved',
      authorization_code: 'AUTH-123456',
      card_brand: 'Visa',
      last_four: '4242',
      processor_message: 'Transacción aprobada',
    }),
    createdAt: '2026-03-01T15:30:00Z',
  },
  {
    id: 2,
    saleId: 2,
    transactionId: 'TXN-20260302-002',
    amount: 131.0,
    status: 'failed',
    paymentMethod: 'yape',
    responseData: JSON.stringify({
      status: 'declined',
      error_code: 'INSUFFICIENT_FUNDS',
      error_message: 'Saldo insuficiente en la cuenta',
      processor_message: 'La transacción no pudo ser completada',
      attempt: 2,
    }),
    createdAt: '2026-03-02T11:20:00Z',
  },
  {
    id: 3,
    saleId: 2,
    transactionId: 'TXN-20260302-003',
    amount: 131.0,
    status: 'completed',
    paymentMethod: 'card',
    responseData: JSON.stringify({
      status: 'approved',
      authorization_code: 'AUTH-789012',
      card_brand: 'Mastercard',
      last_four: '1111',
      processor_message: 'Transacción aprobada',
    }),
    createdAt: '2026-03-02T11:25:00Z',
  },
  {
    id: 4,
    saleId: 3,
    transactionId: 'TXN-20260303-004',
    amount: 249.0,
    status: 'pending',
    paymentMethod: 'transfer',
    responseData: JSON.stringify({
      status: 'pending',
      bank: 'BCP',
      reference: 'REF-20260303-999',
      message: 'Esperando confirmación bancaria',
    }),
    createdAt: '2026-03-03T09:00:00Z',
  },
  {
    id: 5,
    saleId: 5,
    transactionId: 'TXN-20260305-005',
    amount: 199.0,
    status: 'refunded',
    paymentMethod: 'paypal',
    responseData: JSON.stringify({
      status: 'refunded',
      refund_id: 'REFUND-555555',
      reason: 'Solicitud de cancelación del cliente',
      processed_at: '2026-03-06T10:00:00Z',
    }),
    createdAt: '2026-03-05T16:45:00Z',
  },
];

// ─── Mock Vouchers ───
const mockVouchers: IVoucher[] = [
  {
    id: 1,
    saleId: 1,
    voucherType: 'boleta',
    series: 'B001',
    number: '00000123',
    pdfUrl: '',
  },
  {
    id: 2,
    saleId: 4,
    voucherType: 'factura',
    series: 'F001',
    number: '00000089',
    pdfUrl: '',
  },
];

// ─── Mock Sales ───
export const MOCK_SALES: ISale[] = [
  {
    id: 1,
    customerId: 1,
    userId: 1,
    orderNumber: 'ORD-20260301-001',
    status: 'processing',
    subtotal: 298.8,
    discountAmount: 10.0,
    shippingCost: 15.0,
    total: 303.8,
    paymentMethod: 'card',
    notes: 'Cliente solicita entrega rápida',
    createdAt: '2026-03-01T15:30:00Z',
    customerName: 'María García López',
    items: [mockDetails[0], mockDetails[1]],
    vouchers: [mockVouchers[0]],
    paymentTransactions: [mockPayments[0]],
    shipments: [],
  },
  {
    id: 2,
    customerId: 2,
    userId: 1,
    orderNumber: 'ORD-20260302-002',
    status: 'paid',
    subtotal: 131.0,
    discountAmount: 5.5,
    shippingCost: 10.0,
    total: 135.5,
    paymentMethod: 'yape',
    notes: '',
    createdAt: '2026-03-02T11:20:00Z',
    customerName: 'Carlos Mendoza Rivas',
    items: [mockDetails[2]],
    vouchers: [],
    paymentTransactions: [mockPayments[1], mockPayments[2]],
    shipments: [],
  },
  {
    id: 3,
    customerId: 3,
    userId: 2,
    orderNumber: 'ORD-20260303-003',
    status: 'pending',
    subtotal: 249.0,
    discountAmount: 0,
    shippingCost: 20.0,
    total: 269.0,
    paymentMethod: 'transfer',
    notes: 'Transferencia bancaria pendiente de confirmación',
    createdAt: '2026-03-03T09:00:00Z',
    customerName: 'Ana Torres Sánchez',
    items: [mockDetails[3]],
    vouchers: [],
    paymentTransactions: [mockPayments[3]],
    shipments: [],
  },
  {
    id: 4,
    customerId: 4,
    userId: 1,
    orderNumber: 'ORD-20260310-004',
    status: 'delivered',
    subtotal: 79.9,
    discountAmount: 0,
    shippingCost: 12.0,
    total: 91.9,
    paymentMethod: 'cash',
    notes: 'Entregado en recepción del edificio',
    createdAt: '2026-03-10T10:30:00Z',
    customerName: 'Lucía Fernández Paz',
    items: [mockDetails[4]],
    vouchers: [mockVouchers[1]],
    paymentTransactions: [],
    shipments: [mockShipments[0], mockShipments[1]],
  },
  {
    id: 5,
    customerId: 5,
    userId: 2,
    orderNumber: 'ORD-20260305-005',
    status: 'cancelled',
    subtotal: 199.0,
    discountAmount: 0,
    shippingCost: 0,
    total: 199.0,
    paymentMethod: 'paypal',
    notes: 'Cliente canceló por cambio de método de pago',
    createdAt: '2026-03-05T16:45:00Z',
    customerName: 'Pedro Castillo Huerta',
    items: [mockDetails[5], mockDetails[6]],
    vouchers: [],
    paymentTransactions: [mockPayments[4]],
    shipments: [],
  },
  {
    id: 6,
    customerId: 6,
    userId: 1,
    orderNumber: 'ORD-20260315-006',
    status: 'refunded',
    subtotal: 320.0,
    discountAmount: 30.0,
    shippingCost: 0,
    total: 290.0,
    paymentMethod: 'plin',
    notes: 'Reembolso procesado por defecto de fábrica',
    createdAt: '2026-03-15T14:00:00Z',
    customerName: 'Sofía Ramos Díaz',
    items: [],
    vouchers: [],
    paymentTransactions: [],
    shipments: [],
  },
  {
    id: 7,
    customerId: 7,
    userId: 1,
    orderNumber: 'ORD-20260318-007',
    status: 'shipped',
    subtotal: 450.0,
    discountAmount: 0,
    shippingCost: 25.0,
    total: 475.0,
    paymentMethod: 'card',
    notes: '',
    createdAt: '2026-03-18T08:30:00Z',
    customerName: 'Diego Álvarez Campos',
    items: [],
    vouchers: [],
    paymentTransactions: [],
    shipments: [],
  },
];

// ─── Helper to get mock sale by ID ───
export function getMockSaleById(id: number): ISale | undefined {
  return MOCK_SALES.find((s) => s.id === id);
}

// ─── Helper to get mock shipments for a sale ───
export function getMockShipmentsBySaleId(saleId: number): IShipment[] {
  return mockShipments.filter((s) => s.saleId === saleId);
}

// ─── Helper to get mock payments for a sale ───
export function getMockPaymentsBySaleId(saleId: number): IPaymentTransaction[] {
  return mockPayments.filter((p) => p.saleId === saleId);
}

// ─── Helper to get mock vouchers for a sale ───
export function getMockVouchersBySaleId(saleId: number): IVoucher[] {
  return mockVouchers.filter((v) => v.saleId === saleId);
}

// ─── Helper to get mock items for a sale ───
export function getMockItemsBySaleId(saleId: number): ISaleDetail[] {
  return mockDetails.filter((d) => d.saleId === saleId);
}
